-- ============================================================
-- CINEVAULT - Dummy Seed Data (auto-generated)
-- ============================================================
USE cinevault;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE booking_seats;
TRUNCATE TABLE bookings;
TRUNCATE TABLE seats;
TRUNCATE TABLE showtimes;
TRUNCATE TABLE screens;
TRUNCATE TABLE screen_types;
TRUNCATE TABLE theatres;
TRUNCATE TABLE movie_genres;
TRUNCATE TABLE movies;
TRUNCATE TABLE genres;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS = 1;

-- USERS
INSERT INTO users (name, email, password, role) VALUES
('Admin User', 'admin@cinevault.com', 'admin123', 'admin'),
('John Customer', 'user@cinevault.com', 'user123', 'customer'),
('Priya Sharma', 'priyasharma0@example.com', 'pass123', 'customer'),
('Alex Turner', 'alexturner1@example.com', 'pass123', 'customer'),
('Maria Garcia', 'mariagarcia2@example.com', 'pass123', 'customer'),
('Wei Chen', 'weichen3@example.com', 'pass123', 'customer'),
('Sara Khan', 'sarakhan4@example.com', 'pass123', 'customer'),
('Liam Obrien', 'liamobrien5@example.com', 'pass123', 'customer'),
('Nina Patel', 'ninapatel6@example.com', 'pass123', 'customer'),
('Tom Becker', 'tombecker7@example.com', 'pass123', 'customer'),
('Fatima Noor', 'fatimanoor8@example.com', 'pass123', 'customer'),
('Chris Diaz', 'chrisdiaz9@example.com', 'pass123', 'customer');

-- GENRES
INSERT INTO genres (name) VALUES
('Sci-Fi'),
('Thriller'),
('Drama'),
('Action'),
('Comedy'),
('Horror'),
('Romance'),
('Animation');

-- MOVIES
INSERT INTO movies (title, description, poster_url, rating, duration_minutes, director, cast_list, release_date, status) VALUES ('Neon Frontier', 'In 2087, a rogue cartographer discovers a signal from beyond the known star maps, drawing her into a conspiracy that spans three civilizations.', 'https://picsum.photos/seed/movie1/500/750', 'PG-13', 138, 'Yuki Tanaka', 'Elena Vasquez, James Okafor, Petra Novak', '2026-01-10', 'now_showing');
INSERT INTO movies (title, description, poster_url, rating, duration_minutes, director, cast_list, release_date, status) VALUES ('Midnight Ledger', 'A forensic accountant uncovers a decade-old fraud that ties her own family to an unsolved disappearance.', 'https://picsum.photos/seed/movie2/500/750', 'R', 124, 'Marcus Cole', 'David Kim, Rosa Alvarez, Tom Reilly', '2026-02-11', 'now_showing');
INSERT INTO movies (title, description, poster_url, rating, duration_minutes, director, cast_list, release_date, status) VALUES ('Golden Hour', 'Two strangers keep meeting at the same San Francisco overlook every year on the same day, for reasons neither can explain.', 'https://picsum.photos/seed/movie3/500/750', 'PG-13', 109, 'Ingrid Solberg', 'Maya Lin, Owen Brooks, Claire Dupont', '2026-03-12', 'now_showing');
INSERT INTO movies (title, description, poster_url, rating, duration_minutes, director, cast_list, release_date, status) VALUES ('Steel Horizon', 'An engineer must stop a runaway orbital elevator before it tears through the equator.', 'https://picsum.photos/seed/movie4/500/750', 'PG-13', 131, 'Derek Osei', 'Marcus Reed, Tanya Brooks, Victor Hale', '2026-04-13', 'now_showing');
INSERT INTO movies (title, description, poster_url, rating, duration_minutes, director, cast_list, release_date, status) VALUES ('The Quiet Orchard', 'A grieving beekeeper rebuilds her late fathers orchard and, with it, her relationship with her estranged brother.', 'https://picsum.photos/seed/movie5/500/750', 'PG', 101, 'Helene Fischer', 'Anna Voss, Peter Lund, Ingrid Hahn', '2026-05-14', 'now_showing');
INSERT INTO movies (title, description, poster_url, rating, duration_minutes, director, cast_list, release_date, status) VALUES ('Comedy of Errors Inc.', 'A startups worst product launch becomes the best thing that ever happened to its founders.', 'https://picsum.photos/seed/movie6/500/750', 'PG-13', 97, 'Jamal Whitfield', 'Sam Ortiz, Debra Chan, Kyle Nolan', '2026-06-15', 'now_showing');
INSERT INTO movies (title, description, poster_url, rating, duration_minutes, director, cast_list, release_date, status) VALUES ('Hollow Point', 'A retired sniper is pulled back for one last job that was never really about the target.', 'https://picsum.photos/seed/movie7/500/750', 'R', 116, 'Renee Aubert', 'Frank Castillo, Nadia Petrov, Ben Wu', '2026-01-16', 'now_showing');
INSERT INTO movies (title, description, poster_url, rating, duration_minutes, director, cast_list, release_date, status) VALUES ('Whispers in Attic 7', 'A family renovating an old apartment building keeps finding rooms that were never on the blueprints.', 'https://picsum.photos/seed/movie8/500/750', 'R', 98, 'Colin Ashworth', 'Zoe Marlowe, Grant Ellis, Ivy Chen', '2026-02-17', 'now_showing');
INSERT INTO movies (title, description, poster_url, rating, duration_minutes, director, cast_list, release_date, status) VALUES ('Paper Constellations', 'An origami-folding girl discovers her paper creatures come alive on the night of a lunar eclipse.', 'https://picsum.photos/seed/movie9/500/750', 'PG', 94, 'Mio Sakata', 'Voices of Aiko Sato, Leo Marchetti', '2026-03-18', 'now_showing');
INSERT INTO movies (title, description, poster_url, rating, duration_minutes, director, cast_list, release_date, status) VALUES ('Last Exit East', 'Three siblings drive across the country to sell their late mothers diner before the bank forecloses.', 'https://picsum.photos/seed/movie10/500/750', 'PG-13', 122, 'Omar Siddiqui', 'Farah Idris, Noah Kessler, Wendy Zhou', '2026-04-19', 'now_showing');

-- MOVIE GENRES
INSERT INTO movie_genres (movie_id, genre_id) VALUES (1, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (1, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (2, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (2, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (3, 7);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (3, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (4, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (4, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (5, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (6, 5);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (7, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (7, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (8, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (9, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (9, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (10, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (10, 5);

-- THEATRES
INSERT INTO theatres (name, location, city, address, phone, email, status, has_parking, has_food_court, has_wheelchair_access, has_ac) VALUES ('CinéVault Grand Central', 'Midtown Manhattan', 'New York', '350 5th Ave, New York, NY', '212-555-0110', 'grandcentral@cinevault.com', 'active', 1, 1, 1, 1);
INSERT INTO theatres (name, location, city, address, phone, email, status, has_parking, has_food_court, has_wheelchair_access, has_ac) VALUES ('CinéVault Bay View', 'Embarcadero', 'San Francisco', '1 Ferry Building, San Francisco, CA', '415-555-0122', 'bayview@cinevault.com', 'active', 1, 1, 1, 1);
INSERT INTO theatres (name, location, city, address, phone, email, status, has_parking, has_food_court, has_wheelchair_access, has_ac) VALUES ('CinéVault Lakeshore', 'Lakeview', 'Chicago', '2200 N Lakeshore Dr, Chicago, IL', '312-555-0133', 'lakeshore@cinevault.com', 'active', 0, 1, 1, 1);
INSERT INTO theatres (name, location, city, address, phone, email, status, has_parking, has_food_court, has_wheelchair_access, has_ac) VALUES ('CinéVault Sunset Strip', 'West Hollywood', 'Los Angeles', '8600 Sunset Blvd, Los Angeles, CA', '323-555-0144', 'sunset@cinevault.com', 'active', 1, 1, 0, 1);
INSERT INTO theatres (name, location, city, address, phone, email, status, has_parking, has_food_court, has_wheelchair_access, has_ac) VALUES ('CinéVault Harbor Point', 'Seaport District', 'Boston', '10 Harbor Way, Boston, MA', '617-555-0155', 'harborpoint@cinevault.com', 'active', 1, 0, 1, 1);

-- SCREEN TYPES
INSERT INTO screen_types (name) VALUES
('2D'),
('3D'),
('IMAX'),
('4DX'),
('VIP');

-- SCREENS
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (1, 'Screen 1', 1, 108, 9, 12, 1);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (1, 'Screen 2', 2, 140, 10, 14, 2);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (1, 'Screen 3', 3, 80, 8, 10, 3);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (2, 'Screen 1', 1, 108, 9, 12, 4);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (2, 'Screen 2', 2, 140, 10, 14, 5);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (2, 'Screen 3', 3, 80, 8, 10, 1);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (3, 'Screen 1', 1, 108, 9, 12, 2);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (3, 'Screen 2', 2, 140, 10, 14, 3);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (3, 'Screen 3', 3, 80, 8, 10, 4);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (4, 'Screen 1', 1, 108, 9, 12, 5);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (4, 'Screen 2', 2, 140, 10, 14, 1);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (4, 'Screen 3', 3, 80, 8, 10, 2);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (5, 'Screen 1', 1, 108, 9, 12, 3);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (5, 'Screen 2', 2, 140, 10, 14, 4);
INSERT INTO screens (theatre_id, screen_name, screen_number, capacity, rows_count, columns_count, screen_type_id) VALUES (5, 'Screen 3', 3, 80, 8, 10, 5);

-- SEATS
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(1, 'A', 1, 'standard'),
(1, 'A', 2, 'standard'),
(1, 'A', 3, 'standard'),
(1, 'A', 4, 'standard'),
(1, 'A', 5, 'standard'),
(1, 'A', 6, 'standard'),
(1, 'A', 7, 'standard'),
(1, 'A', 8, 'standard'),
(1, 'A', 9, 'standard'),
(1, 'A', 10, 'standard'),
(1, 'A', 11, 'standard'),
(1, 'A', 12, 'standard'),
(1, 'B', 1, 'standard'),
(1, 'B', 2, 'standard'),
(1, 'B', 3, 'standard'),
(1, 'B', 4, 'standard'),
(1, 'B', 5, 'standard'),
(1, 'B', 6, 'standard'),
(1, 'B', 7, 'standard'),
(1, 'B', 8, 'standard'),
(1, 'B', 9, 'standard'),
(1, 'B', 10, 'standard'),
(1, 'B', 11, 'standard'),
(1, 'B', 12, 'standard'),
(1, 'C', 1, 'standard'),
(1, 'C', 2, 'standard'),
(1, 'C', 3, 'standard'),
(1, 'C', 4, 'standard'),
(1, 'C', 5, 'standard'),
(1, 'C', 6, 'standard'),
(1, 'C', 7, 'standard'),
(1, 'C', 8, 'standard'),
(1, 'C', 9, 'standard'),
(1, 'C', 10, 'standard'),
(1, 'C', 11, 'standard'),
(1, 'C', 12, 'standard'),
(1, 'D', 1, 'standard'),
(1, 'D', 2, 'standard'),
(1, 'D', 3, 'standard'),
(1, 'D', 4, 'standard'),
(1, 'D', 5, 'standard'),
(1, 'D', 6, 'standard'),
(1, 'D', 7, 'standard'),
(1, 'D', 8, 'standard'),
(1, 'D', 9, 'standard'),
(1, 'D', 10, 'standard'),
(1, 'D', 11, 'standard'),
(1, 'D', 12, 'standard'),
(1, 'E', 1, 'standard'),
(1, 'E', 2, 'standard'),
(1, 'E', 3, 'standard'),
(1, 'E', 4, 'standard'),
(1, 'E', 5, 'standard'),
(1, 'E', 6, 'standard'),
(1, 'E', 7, 'standard'),
(1, 'E', 8, 'standard'),
(1, 'E', 9, 'standard'),
(1, 'E', 10, 'standard'),
(1, 'E', 11, 'standard'),
(1, 'E', 12, 'standard'),
(1, 'F', 1, 'standard'),
(1, 'F', 2, 'standard'),
(1, 'F', 3, 'standard'),
(1, 'F', 4, 'standard'),
(1, 'F', 5, 'standard'),
(1, 'F', 6, 'standard'),
(1, 'F', 7, 'standard'),
(1, 'F', 8, 'standard'),
(1, 'F', 9, 'standard'),
(1, 'F', 10, 'standard'),
(1, 'F', 11, 'standard'),
(1, 'F', 12, 'standard'),
(1, 'G', 1, 'standard'),
(1, 'G', 2, 'standard'),
(1, 'G', 3, 'standard'),
(1, 'G', 4, 'standard'),
(1, 'G', 5, 'standard'),
(1, 'G', 6, 'standard'),
(1, 'G', 7, 'standard'),
(1, 'G', 8, 'standard'),
(1, 'G', 9, 'standard'),
(1, 'G', 10, 'standard'),
(1, 'G', 11, 'standard'),
(1, 'G', 12, 'standard'),
(1, 'H', 1, 'standard'),
(1, 'H', 2, 'standard'),
(1, 'H', 3, 'standard'),
(1, 'H', 4, 'standard'),
(1, 'H', 5, 'standard'),
(1, 'H', 6, 'standard'),
(1, 'H', 7, 'standard'),
(1, 'H', 8, 'standard'),
(1, 'H', 9, 'standard'),
(1, 'H', 10, 'standard'),
(1, 'H', 11, 'standard'),
(1, 'H', 12, 'standard'),
(1, 'I', 1, 'vip'),
(1, 'I', 2, 'vip'),
(1, 'I', 3, 'vip'),
(1, 'I', 4, 'vip'),
(1, 'I', 5, 'vip'),
(1, 'I', 6, 'vip'),
(1, 'I', 7, 'vip'),
(1, 'I', 8, 'vip'),
(1, 'I', 9, 'vip'),
(1, 'I', 10, 'vip'),
(1, 'I', 11, 'vip'),
(1, 'I', 12, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(2, 'A', 1, 'standard'),
(2, 'A', 2, 'standard'),
(2, 'A', 3, 'standard'),
(2, 'A', 4, 'standard'),
(2, 'A', 5, 'standard'),
(2, 'A', 6, 'standard'),
(2, 'A', 7, 'standard'),
(2, 'A', 8, 'standard'),
(2, 'A', 9, 'standard'),
(2, 'A', 10, 'standard'),
(2, 'A', 11, 'standard'),
(2, 'A', 12, 'standard'),
(2, 'A', 13, 'standard'),
(2, 'A', 14, 'standard'),
(2, 'B', 1, 'standard'),
(2, 'B', 2, 'standard'),
(2, 'B', 3, 'standard'),
(2, 'B', 4, 'standard'),
(2, 'B', 5, 'standard'),
(2, 'B', 6, 'standard'),
(2, 'B', 7, 'standard'),
(2, 'B', 8, 'standard'),
(2, 'B', 9, 'standard'),
(2, 'B', 10, 'standard'),
(2, 'B', 11, 'standard'),
(2, 'B', 12, 'standard'),
(2, 'B', 13, 'standard'),
(2, 'B', 14, 'standard'),
(2, 'C', 1, 'standard'),
(2, 'C', 2, 'standard'),
(2, 'C', 3, 'standard'),
(2, 'C', 4, 'standard'),
(2, 'C', 5, 'standard'),
(2, 'C', 6, 'standard'),
(2, 'C', 7, 'standard'),
(2, 'C', 8, 'standard'),
(2, 'C', 9, 'standard'),
(2, 'C', 10, 'standard'),
(2, 'C', 11, 'standard'),
(2, 'C', 12, 'standard'),
(2, 'C', 13, 'standard'),
(2, 'C', 14, 'standard'),
(2, 'D', 1, 'standard'),
(2, 'D', 2, 'standard'),
(2, 'D', 3, 'standard'),
(2, 'D', 4, 'standard'),
(2, 'D', 5, 'standard'),
(2, 'D', 6, 'standard'),
(2, 'D', 7, 'standard'),
(2, 'D', 8, 'standard'),
(2, 'D', 9, 'standard'),
(2, 'D', 10, 'standard'),
(2, 'D', 11, 'standard'),
(2, 'D', 12, 'standard'),
(2, 'D', 13, 'standard'),
(2, 'D', 14, 'standard'),
(2, 'E', 1, 'standard'),
(2, 'E', 2, 'standard'),
(2, 'E', 3, 'standard'),
(2, 'E', 4, 'standard'),
(2, 'E', 5, 'standard'),
(2, 'E', 6, 'standard'),
(2, 'E', 7, 'standard'),
(2, 'E', 8, 'standard'),
(2, 'E', 9, 'standard'),
(2, 'E', 10, 'standard'),
(2, 'E', 11, 'standard'),
(2, 'E', 12, 'standard'),
(2, 'E', 13, 'standard'),
(2, 'E', 14, 'standard'),
(2, 'F', 1, 'standard'),
(2, 'F', 2, 'standard'),
(2, 'F', 3, 'standard'),
(2, 'F', 4, 'standard'),
(2, 'F', 5, 'standard'),
(2, 'F', 6, 'standard'),
(2, 'F', 7, 'standard'),
(2, 'F', 8, 'standard'),
(2, 'F', 9, 'standard'),
(2, 'F', 10, 'standard'),
(2, 'F', 11, 'standard'),
(2, 'F', 12, 'standard'),
(2, 'F', 13, 'standard'),
(2, 'F', 14, 'standard'),
(2, 'G', 1, 'standard'),
(2, 'G', 2, 'standard'),
(2, 'G', 3, 'standard'),
(2, 'G', 4, 'standard'),
(2, 'G', 5, 'standard'),
(2, 'G', 6, 'standard'),
(2, 'G', 7, 'standard'),
(2, 'G', 8, 'standard'),
(2, 'G', 9, 'standard'),
(2, 'G', 10, 'standard'),
(2, 'G', 11, 'standard'),
(2, 'G', 12, 'standard'),
(2, 'G', 13, 'standard'),
(2, 'G', 14, 'standard'),
(2, 'H', 1, 'standard'),
(2, 'H', 2, 'standard'),
(2, 'H', 3, 'standard'),
(2, 'H', 4, 'standard'),
(2, 'H', 5, 'standard'),
(2, 'H', 6, 'standard'),
(2, 'H', 7, 'standard'),
(2, 'H', 8, 'standard'),
(2, 'H', 9, 'standard'),
(2, 'H', 10, 'standard'),
(2, 'H', 11, 'standard'),
(2, 'H', 12, 'standard'),
(2, 'H', 13, 'standard'),
(2, 'H', 14, 'standard'),
(2, 'I', 1, 'standard'),
(2, 'I', 2, 'standard'),
(2, 'I', 3, 'standard'),
(2, 'I', 4, 'standard'),
(2, 'I', 5, 'standard'),
(2, 'I', 6, 'standard'),
(2, 'I', 7, 'standard'),
(2, 'I', 8, 'standard'),
(2, 'I', 9, 'standard'),
(2, 'I', 10, 'standard'),
(2, 'I', 11, 'standard'),
(2, 'I', 12, 'standard'),
(2, 'I', 13, 'standard'),
(2, 'I', 14, 'standard'),
(2, 'J', 1, 'vip'),
(2, 'J', 2, 'vip'),
(2, 'J', 3, 'vip'),
(2, 'J', 4, 'vip'),
(2, 'J', 5, 'vip'),
(2, 'J', 6, 'vip'),
(2, 'J', 7, 'vip'),
(2, 'J', 8, 'vip'),
(2, 'J', 9, 'vip'),
(2, 'J', 10, 'vip'),
(2, 'J', 11, 'vip'),
(2, 'J', 12, 'vip'),
(2, 'J', 13, 'vip'),
(2, 'J', 14, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(3, 'A', 1, 'standard'),
(3, 'A', 2, 'standard'),
(3, 'A', 3, 'standard'),
(3, 'A', 4, 'standard'),
(3, 'A', 5, 'standard'),
(3, 'A', 6, 'standard'),
(3, 'A', 7, 'standard'),
(3, 'A', 8, 'standard'),
(3, 'A', 9, 'standard'),
(3, 'A', 10, 'standard'),
(3, 'B', 1, 'standard'),
(3, 'B', 2, 'standard'),
(3, 'B', 3, 'standard'),
(3, 'B', 4, 'standard'),
(3, 'B', 5, 'standard'),
(3, 'B', 6, 'standard'),
(3, 'B', 7, 'standard'),
(3, 'B', 8, 'standard'),
(3, 'B', 9, 'standard'),
(3, 'B', 10, 'standard'),
(3, 'C', 1, 'standard'),
(3, 'C', 2, 'standard'),
(3, 'C', 3, 'standard'),
(3, 'C', 4, 'standard'),
(3, 'C', 5, 'standard'),
(3, 'C', 6, 'standard'),
(3, 'C', 7, 'standard'),
(3, 'C', 8, 'standard'),
(3, 'C', 9, 'standard'),
(3, 'C', 10, 'standard'),
(3, 'D', 1, 'standard'),
(3, 'D', 2, 'standard'),
(3, 'D', 3, 'standard'),
(3, 'D', 4, 'standard'),
(3, 'D', 5, 'standard'),
(3, 'D', 6, 'standard'),
(3, 'D', 7, 'standard'),
(3, 'D', 8, 'standard'),
(3, 'D', 9, 'standard'),
(3, 'D', 10, 'standard'),
(3, 'E', 1, 'standard'),
(3, 'E', 2, 'standard'),
(3, 'E', 3, 'standard'),
(3, 'E', 4, 'standard'),
(3, 'E', 5, 'standard'),
(3, 'E', 6, 'standard'),
(3, 'E', 7, 'standard'),
(3, 'E', 8, 'standard'),
(3, 'E', 9, 'standard'),
(3, 'E', 10, 'standard'),
(3, 'F', 1, 'standard'),
(3, 'F', 2, 'standard'),
(3, 'F', 3, 'standard'),
(3, 'F', 4, 'standard'),
(3, 'F', 5, 'standard'),
(3, 'F', 6, 'standard'),
(3, 'F', 7, 'standard'),
(3, 'F', 8, 'standard'),
(3, 'F', 9, 'standard'),
(3, 'F', 10, 'standard'),
(3, 'G', 1, 'standard'),
(3, 'G', 2, 'standard'),
(3, 'G', 3, 'standard'),
(3, 'G', 4, 'standard'),
(3, 'G', 5, 'standard'),
(3, 'G', 6, 'standard'),
(3, 'G', 7, 'standard'),
(3, 'G', 8, 'standard'),
(3, 'G', 9, 'standard'),
(3, 'G', 10, 'standard'),
(3, 'H', 1, 'vip'),
(3, 'H', 2, 'vip'),
(3, 'H', 3, 'vip'),
(3, 'H', 4, 'vip'),
(3, 'H', 5, 'vip'),
(3, 'H', 6, 'vip'),
(3, 'H', 7, 'vip'),
(3, 'H', 8, 'vip'),
(3, 'H', 9, 'vip'),
(3, 'H', 10, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(4, 'A', 1, 'standard'),
(4, 'A', 2, 'standard'),
(4, 'A', 3, 'standard'),
(4, 'A', 4, 'standard'),
(4, 'A', 5, 'standard'),
(4, 'A', 6, 'standard'),
(4, 'A', 7, 'standard'),
(4, 'A', 8, 'standard'),
(4, 'A', 9, 'standard'),
(4, 'A', 10, 'standard'),
(4, 'A', 11, 'standard'),
(4, 'A', 12, 'standard'),
(4, 'B', 1, 'standard'),
(4, 'B', 2, 'standard'),
(4, 'B', 3, 'standard'),
(4, 'B', 4, 'standard'),
(4, 'B', 5, 'standard'),
(4, 'B', 6, 'standard'),
(4, 'B', 7, 'standard'),
(4, 'B', 8, 'standard'),
(4, 'B', 9, 'standard'),
(4, 'B', 10, 'standard'),
(4, 'B', 11, 'standard'),
(4, 'B', 12, 'standard'),
(4, 'C', 1, 'standard'),
(4, 'C', 2, 'standard'),
(4, 'C', 3, 'standard'),
(4, 'C', 4, 'standard'),
(4, 'C', 5, 'standard'),
(4, 'C', 6, 'standard'),
(4, 'C', 7, 'standard'),
(4, 'C', 8, 'standard'),
(4, 'C', 9, 'standard'),
(4, 'C', 10, 'standard'),
(4, 'C', 11, 'standard'),
(4, 'C', 12, 'standard'),
(4, 'D', 1, 'standard'),
(4, 'D', 2, 'standard'),
(4, 'D', 3, 'standard'),
(4, 'D', 4, 'standard'),
(4, 'D', 5, 'standard'),
(4, 'D', 6, 'standard'),
(4, 'D', 7, 'standard'),
(4, 'D', 8, 'standard'),
(4, 'D', 9, 'standard'),
(4, 'D', 10, 'standard'),
(4, 'D', 11, 'standard'),
(4, 'D', 12, 'standard'),
(4, 'E', 1, 'standard'),
(4, 'E', 2, 'standard'),
(4, 'E', 3, 'standard'),
(4, 'E', 4, 'standard'),
(4, 'E', 5, 'standard'),
(4, 'E', 6, 'standard'),
(4, 'E', 7, 'standard'),
(4, 'E', 8, 'standard'),
(4, 'E', 9, 'standard'),
(4, 'E', 10, 'standard'),
(4, 'E', 11, 'standard'),
(4, 'E', 12, 'standard'),
(4, 'F', 1, 'standard'),
(4, 'F', 2, 'standard'),
(4, 'F', 3, 'standard'),
(4, 'F', 4, 'standard'),
(4, 'F', 5, 'standard'),
(4, 'F', 6, 'standard'),
(4, 'F', 7, 'standard'),
(4, 'F', 8, 'standard'),
(4, 'F', 9, 'standard'),
(4, 'F', 10, 'standard'),
(4, 'F', 11, 'standard'),
(4, 'F', 12, 'standard'),
(4, 'G', 1, 'standard'),
(4, 'G', 2, 'standard'),
(4, 'G', 3, 'standard'),
(4, 'G', 4, 'standard'),
(4, 'G', 5, 'standard'),
(4, 'G', 6, 'standard'),
(4, 'G', 7, 'standard'),
(4, 'G', 8, 'standard'),
(4, 'G', 9, 'standard'),
(4, 'G', 10, 'standard'),
(4, 'G', 11, 'standard'),
(4, 'G', 12, 'standard'),
(4, 'H', 1, 'standard'),
(4, 'H', 2, 'standard'),
(4, 'H', 3, 'standard'),
(4, 'H', 4, 'standard'),
(4, 'H', 5, 'standard'),
(4, 'H', 6, 'standard'),
(4, 'H', 7, 'standard'),
(4, 'H', 8, 'standard'),
(4, 'H', 9, 'standard'),
(4, 'H', 10, 'standard'),
(4, 'H', 11, 'standard'),
(4, 'H', 12, 'standard'),
(4, 'I', 1, 'vip'),
(4, 'I', 2, 'vip'),
(4, 'I', 3, 'vip'),
(4, 'I', 4, 'vip'),
(4, 'I', 5, 'vip'),
(4, 'I', 6, 'vip'),
(4, 'I', 7, 'vip'),
(4, 'I', 8, 'vip'),
(4, 'I', 9, 'vip'),
(4, 'I', 10, 'vip'),
(4, 'I', 11, 'vip'),
(4, 'I', 12, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(5, 'A', 1, 'standard'),
(5, 'A', 2, 'standard'),
(5, 'A', 3, 'standard'),
(5, 'A', 4, 'standard'),
(5, 'A', 5, 'standard'),
(5, 'A', 6, 'standard'),
(5, 'A', 7, 'standard'),
(5, 'A', 8, 'standard'),
(5, 'A', 9, 'standard'),
(5, 'A', 10, 'standard'),
(5, 'A', 11, 'standard'),
(5, 'A', 12, 'standard'),
(5, 'A', 13, 'standard'),
(5, 'A', 14, 'standard'),
(5, 'B', 1, 'standard'),
(5, 'B', 2, 'standard'),
(5, 'B', 3, 'standard'),
(5, 'B', 4, 'standard'),
(5, 'B', 5, 'standard'),
(5, 'B', 6, 'standard'),
(5, 'B', 7, 'standard'),
(5, 'B', 8, 'standard'),
(5, 'B', 9, 'standard'),
(5, 'B', 10, 'standard'),
(5, 'B', 11, 'standard'),
(5, 'B', 12, 'standard'),
(5, 'B', 13, 'standard'),
(5, 'B', 14, 'standard'),
(5, 'C', 1, 'standard'),
(5, 'C', 2, 'standard'),
(5, 'C', 3, 'standard'),
(5, 'C', 4, 'standard'),
(5, 'C', 5, 'standard'),
(5, 'C', 6, 'standard'),
(5, 'C', 7, 'standard'),
(5, 'C', 8, 'standard'),
(5, 'C', 9, 'standard'),
(5, 'C', 10, 'standard'),
(5, 'C', 11, 'standard'),
(5, 'C', 12, 'standard'),
(5, 'C', 13, 'standard'),
(5, 'C', 14, 'standard'),
(5, 'D', 1, 'standard'),
(5, 'D', 2, 'standard'),
(5, 'D', 3, 'standard'),
(5, 'D', 4, 'standard'),
(5, 'D', 5, 'standard'),
(5, 'D', 6, 'standard'),
(5, 'D', 7, 'standard'),
(5, 'D', 8, 'standard'),
(5, 'D', 9, 'standard'),
(5, 'D', 10, 'standard'),
(5, 'D', 11, 'standard'),
(5, 'D', 12, 'standard'),
(5, 'D', 13, 'standard'),
(5, 'D', 14, 'standard'),
(5, 'E', 1, 'standard'),
(5, 'E', 2, 'standard'),
(5, 'E', 3, 'standard'),
(5, 'E', 4, 'standard'),
(5, 'E', 5, 'standard'),
(5, 'E', 6, 'standard'),
(5, 'E', 7, 'standard'),
(5, 'E', 8, 'standard'),
(5, 'E', 9, 'standard'),
(5, 'E', 10, 'standard'),
(5, 'E', 11, 'standard'),
(5, 'E', 12, 'standard'),
(5, 'E', 13, 'standard'),
(5, 'E', 14, 'standard'),
(5, 'F', 1, 'standard'),
(5, 'F', 2, 'standard'),
(5, 'F', 3, 'standard'),
(5, 'F', 4, 'standard'),
(5, 'F', 5, 'standard'),
(5, 'F', 6, 'standard'),
(5, 'F', 7, 'standard'),
(5, 'F', 8, 'standard'),
(5, 'F', 9, 'standard'),
(5, 'F', 10, 'standard'),
(5, 'F', 11, 'standard'),
(5, 'F', 12, 'standard'),
(5, 'F', 13, 'standard'),
(5, 'F', 14, 'standard'),
(5, 'G', 1, 'standard'),
(5, 'G', 2, 'standard'),
(5, 'G', 3, 'standard'),
(5, 'G', 4, 'standard'),
(5, 'G', 5, 'standard'),
(5, 'G', 6, 'standard'),
(5, 'G', 7, 'standard'),
(5, 'G', 8, 'standard'),
(5, 'G', 9, 'standard'),
(5, 'G', 10, 'standard'),
(5, 'G', 11, 'standard'),
(5, 'G', 12, 'standard'),
(5, 'G', 13, 'standard'),
(5, 'G', 14, 'standard'),
(5, 'H', 1, 'standard'),
(5, 'H', 2, 'standard'),
(5, 'H', 3, 'standard'),
(5, 'H', 4, 'standard'),
(5, 'H', 5, 'standard'),
(5, 'H', 6, 'standard'),
(5, 'H', 7, 'standard'),
(5, 'H', 8, 'standard'),
(5, 'H', 9, 'standard'),
(5, 'H', 10, 'standard'),
(5, 'H', 11, 'standard'),
(5, 'H', 12, 'standard'),
(5, 'H', 13, 'standard'),
(5, 'H', 14, 'standard'),
(5, 'I', 1, 'standard'),
(5, 'I', 2, 'standard'),
(5, 'I', 3, 'standard'),
(5, 'I', 4, 'standard'),
(5, 'I', 5, 'standard'),
(5, 'I', 6, 'standard'),
(5, 'I', 7, 'standard'),
(5, 'I', 8, 'standard'),
(5, 'I', 9, 'standard'),
(5, 'I', 10, 'standard'),
(5, 'I', 11, 'standard'),
(5, 'I', 12, 'standard'),
(5, 'I', 13, 'standard'),
(5, 'I', 14, 'standard'),
(5, 'J', 1, 'vip'),
(5, 'J', 2, 'vip'),
(5, 'J', 3, 'vip'),
(5, 'J', 4, 'vip'),
(5, 'J', 5, 'vip'),
(5, 'J', 6, 'vip'),
(5, 'J', 7, 'vip'),
(5, 'J', 8, 'vip'),
(5, 'J', 9, 'vip'),
(5, 'J', 10, 'vip'),
(5, 'J', 11, 'vip'),
(5, 'J', 12, 'vip'),
(5, 'J', 13, 'vip'),
(5, 'J', 14, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(6, 'A', 1, 'standard'),
(6, 'A', 2, 'standard'),
(6, 'A', 3, 'standard'),
(6, 'A', 4, 'standard'),
(6, 'A', 5, 'standard'),
(6, 'A', 6, 'standard'),
(6, 'A', 7, 'standard'),
(6, 'A', 8, 'standard'),
(6, 'A', 9, 'standard'),
(6, 'A', 10, 'standard'),
(6, 'B', 1, 'standard'),
(6, 'B', 2, 'standard'),
(6, 'B', 3, 'standard'),
(6, 'B', 4, 'standard'),
(6, 'B', 5, 'standard'),
(6, 'B', 6, 'standard'),
(6, 'B', 7, 'standard'),
(6, 'B', 8, 'standard'),
(6, 'B', 9, 'standard'),
(6, 'B', 10, 'standard'),
(6, 'C', 1, 'standard'),
(6, 'C', 2, 'standard'),
(6, 'C', 3, 'standard'),
(6, 'C', 4, 'standard'),
(6, 'C', 5, 'standard'),
(6, 'C', 6, 'standard'),
(6, 'C', 7, 'standard'),
(6, 'C', 8, 'standard'),
(6, 'C', 9, 'standard'),
(6, 'C', 10, 'standard'),
(6, 'D', 1, 'standard'),
(6, 'D', 2, 'standard'),
(6, 'D', 3, 'standard'),
(6, 'D', 4, 'standard'),
(6, 'D', 5, 'standard'),
(6, 'D', 6, 'standard'),
(6, 'D', 7, 'standard'),
(6, 'D', 8, 'standard'),
(6, 'D', 9, 'standard'),
(6, 'D', 10, 'standard'),
(6, 'E', 1, 'standard'),
(6, 'E', 2, 'standard'),
(6, 'E', 3, 'standard'),
(6, 'E', 4, 'standard'),
(6, 'E', 5, 'standard'),
(6, 'E', 6, 'standard'),
(6, 'E', 7, 'standard'),
(6, 'E', 8, 'standard'),
(6, 'E', 9, 'standard'),
(6, 'E', 10, 'standard'),
(6, 'F', 1, 'standard'),
(6, 'F', 2, 'standard'),
(6, 'F', 3, 'standard'),
(6, 'F', 4, 'standard'),
(6, 'F', 5, 'standard'),
(6, 'F', 6, 'standard'),
(6, 'F', 7, 'standard'),
(6, 'F', 8, 'standard'),
(6, 'F', 9, 'standard'),
(6, 'F', 10, 'standard'),
(6, 'G', 1, 'standard'),
(6, 'G', 2, 'standard'),
(6, 'G', 3, 'standard'),
(6, 'G', 4, 'standard'),
(6, 'G', 5, 'standard'),
(6, 'G', 6, 'standard'),
(6, 'G', 7, 'standard'),
(6, 'G', 8, 'standard'),
(6, 'G', 9, 'standard'),
(6, 'G', 10, 'standard'),
(6, 'H', 1, 'vip'),
(6, 'H', 2, 'vip'),
(6, 'H', 3, 'vip'),
(6, 'H', 4, 'vip'),
(6, 'H', 5, 'vip'),
(6, 'H', 6, 'vip'),
(6, 'H', 7, 'vip'),
(6, 'H', 8, 'vip'),
(6, 'H', 9, 'vip'),
(6, 'H', 10, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(7, 'A', 1, 'standard'),
(7, 'A', 2, 'standard'),
(7, 'A', 3, 'standard'),
(7, 'A', 4, 'standard'),
(7, 'A', 5, 'standard'),
(7, 'A', 6, 'standard'),
(7, 'A', 7, 'standard'),
(7, 'A', 8, 'standard'),
(7, 'A', 9, 'standard'),
(7, 'A', 10, 'standard'),
(7, 'A', 11, 'standard'),
(7, 'A', 12, 'standard'),
(7, 'B', 1, 'standard'),
(7, 'B', 2, 'standard'),
(7, 'B', 3, 'standard'),
(7, 'B', 4, 'standard'),
(7, 'B', 5, 'standard'),
(7, 'B', 6, 'standard'),
(7, 'B', 7, 'standard'),
(7, 'B', 8, 'standard'),
(7, 'B', 9, 'standard'),
(7, 'B', 10, 'standard'),
(7, 'B', 11, 'standard'),
(7, 'B', 12, 'standard'),
(7, 'C', 1, 'standard'),
(7, 'C', 2, 'standard'),
(7, 'C', 3, 'standard'),
(7, 'C', 4, 'standard'),
(7, 'C', 5, 'standard'),
(7, 'C', 6, 'standard'),
(7, 'C', 7, 'standard'),
(7, 'C', 8, 'standard'),
(7, 'C', 9, 'standard'),
(7, 'C', 10, 'standard'),
(7, 'C', 11, 'standard'),
(7, 'C', 12, 'standard'),
(7, 'D', 1, 'standard'),
(7, 'D', 2, 'standard'),
(7, 'D', 3, 'standard'),
(7, 'D', 4, 'standard'),
(7, 'D', 5, 'standard'),
(7, 'D', 6, 'standard'),
(7, 'D', 7, 'standard'),
(7, 'D', 8, 'standard'),
(7, 'D', 9, 'standard'),
(7, 'D', 10, 'standard'),
(7, 'D', 11, 'standard'),
(7, 'D', 12, 'standard'),
(7, 'E', 1, 'standard'),
(7, 'E', 2, 'standard'),
(7, 'E', 3, 'standard'),
(7, 'E', 4, 'standard'),
(7, 'E', 5, 'standard'),
(7, 'E', 6, 'standard'),
(7, 'E', 7, 'standard'),
(7, 'E', 8, 'standard'),
(7, 'E', 9, 'standard'),
(7, 'E', 10, 'standard'),
(7, 'E', 11, 'standard'),
(7, 'E', 12, 'standard'),
(7, 'F', 1, 'standard'),
(7, 'F', 2, 'standard'),
(7, 'F', 3, 'standard'),
(7, 'F', 4, 'standard'),
(7, 'F', 5, 'standard'),
(7, 'F', 6, 'standard'),
(7, 'F', 7, 'standard'),
(7, 'F', 8, 'standard'),
(7, 'F', 9, 'standard'),
(7, 'F', 10, 'standard'),
(7, 'F', 11, 'standard'),
(7, 'F', 12, 'standard'),
(7, 'G', 1, 'standard'),
(7, 'G', 2, 'standard'),
(7, 'G', 3, 'standard'),
(7, 'G', 4, 'standard'),
(7, 'G', 5, 'standard'),
(7, 'G', 6, 'standard'),
(7, 'G', 7, 'standard'),
(7, 'G', 8, 'standard'),
(7, 'G', 9, 'standard'),
(7, 'G', 10, 'standard'),
(7, 'G', 11, 'standard'),
(7, 'G', 12, 'standard'),
(7, 'H', 1, 'standard'),
(7, 'H', 2, 'standard'),
(7, 'H', 3, 'standard'),
(7, 'H', 4, 'standard'),
(7, 'H', 5, 'standard'),
(7, 'H', 6, 'standard'),
(7, 'H', 7, 'standard'),
(7, 'H', 8, 'standard'),
(7, 'H', 9, 'standard'),
(7, 'H', 10, 'standard'),
(7, 'H', 11, 'standard'),
(7, 'H', 12, 'standard'),
(7, 'I', 1, 'vip'),
(7, 'I', 2, 'vip'),
(7, 'I', 3, 'vip'),
(7, 'I', 4, 'vip'),
(7, 'I', 5, 'vip'),
(7, 'I', 6, 'vip'),
(7, 'I', 7, 'vip'),
(7, 'I', 8, 'vip'),
(7, 'I', 9, 'vip'),
(7, 'I', 10, 'vip'),
(7, 'I', 11, 'vip'),
(7, 'I', 12, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(8, 'A', 1, 'standard'),
(8, 'A', 2, 'standard'),
(8, 'A', 3, 'standard'),
(8, 'A', 4, 'standard'),
(8, 'A', 5, 'standard'),
(8, 'A', 6, 'standard'),
(8, 'A', 7, 'standard'),
(8, 'A', 8, 'standard'),
(8, 'A', 9, 'standard'),
(8, 'A', 10, 'standard'),
(8, 'A', 11, 'standard'),
(8, 'A', 12, 'standard'),
(8, 'A', 13, 'standard'),
(8, 'A', 14, 'standard'),
(8, 'B', 1, 'standard'),
(8, 'B', 2, 'standard'),
(8, 'B', 3, 'standard'),
(8, 'B', 4, 'standard'),
(8, 'B', 5, 'standard'),
(8, 'B', 6, 'standard'),
(8, 'B', 7, 'standard'),
(8, 'B', 8, 'standard'),
(8, 'B', 9, 'standard'),
(8, 'B', 10, 'standard'),
(8, 'B', 11, 'standard'),
(8, 'B', 12, 'standard'),
(8, 'B', 13, 'standard'),
(8, 'B', 14, 'standard'),
(8, 'C', 1, 'standard'),
(8, 'C', 2, 'standard'),
(8, 'C', 3, 'standard'),
(8, 'C', 4, 'standard'),
(8, 'C', 5, 'standard'),
(8, 'C', 6, 'standard'),
(8, 'C', 7, 'standard'),
(8, 'C', 8, 'standard'),
(8, 'C', 9, 'standard'),
(8, 'C', 10, 'standard'),
(8, 'C', 11, 'standard'),
(8, 'C', 12, 'standard'),
(8, 'C', 13, 'standard'),
(8, 'C', 14, 'standard'),
(8, 'D', 1, 'standard'),
(8, 'D', 2, 'standard'),
(8, 'D', 3, 'standard'),
(8, 'D', 4, 'standard'),
(8, 'D', 5, 'standard'),
(8, 'D', 6, 'standard'),
(8, 'D', 7, 'standard'),
(8, 'D', 8, 'standard'),
(8, 'D', 9, 'standard'),
(8, 'D', 10, 'standard'),
(8, 'D', 11, 'standard'),
(8, 'D', 12, 'standard'),
(8, 'D', 13, 'standard'),
(8, 'D', 14, 'standard'),
(8, 'E', 1, 'standard'),
(8, 'E', 2, 'standard'),
(8, 'E', 3, 'standard'),
(8, 'E', 4, 'standard'),
(8, 'E', 5, 'standard'),
(8, 'E', 6, 'standard'),
(8, 'E', 7, 'standard'),
(8, 'E', 8, 'standard'),
(8, 'E', 9, 'standard'),
(8, 'E', 10, 'standard'),
(8, 'E', 11, 'standard'),
(8, 'E', 12, 'standard'),
(8, 'E', 13, 'standard'),
(8, 'E', 14, 'standard'),
(8, 'F', 1, 'standard'),
(8, 'F', 2, 'standard'),
(8, 'F', 3, 'standard'),
(8, 'F', 4, 'standard'),
(8, 'F', 5, 'standard'),
(8, 'F', 6, 'standard'),
(8, 'F', 7, 'standard'),
(8, 'F', 8, 'standard'),
(8, 'F', 9, 'standard'),
(8, 'F', 10, 'standard'),
(8, 'F', 11, 'standard'),
(8, 'F', 12, 'standard'),
(8, 'F', 13, 'standard'),
(8, 'F', 14, 'standard'),
(8, 'G', 1, 'standard'),
(8, 'G', 2, 'standard'),
(8, 'G', 3, 'standard'),
(8, 'G', 4, 'standard'),
(8, 'G', 5, 'standard'),
(8, 'G', 6, 'standard'),
(8, 'G', 7, 'standard'),
(8, 'G', 8, 'standard'),
(8, 'G', 9, 'standard'),
(8, 'G', 10, 'standard'),
(8, 'G', 11, 'standard'),
(8, 'G', 12, 'standard'),
(8, 'G', 13, 'standard'),
(8, 'G', 14, 'standard'),
(8, 'H', 1, 'standard'),
(8, 'H', 2, 'standard'),
(8, 'H', 3, 'standard'),
(8, 'H', 4, 'standard'),
(8, 'H', 5, 'standard'),
(8, 'H', 6, 'standard'),
(8, 'H', 7, 'standard'),
(8, 'H', 8, 'standard'),
(8, 'H', 9, 'standard'),
(8, 'H', 10, 'standard'),
(8, 'H', 11, 'standard'),
(8, 'H', 12, 'standard'),
(8, 'H', 13, 'standard'),
(8, 'H', 14, 'standard'),
(8, 'I', 1, 'standard'),
(8, 'I', 2, 'standard'),
(8, 'I', 3, 'standard'),
(8, 'I', 4, 'standard'),
(8, 'I', 5, 'standard'),
(8, 'I', 6, 'standard'),
(8, 'I', 7, 'standard'),
(8, 'I', 8, 'standard'),
(8, 'I', 9, 'standard'),
(8, 'I', 10, 'standard'),
(8, 'I', 11, 'standard'),
(8, 'I', 12, 'standard'),
(8, 'I', 13, 'standard'),
(8, 'I', 14, 'standard'),
(8, 'J', 1, 'vip'),
(8, 'J', 2, 'vip'),
(8, 'J', 3, 'vip'),
(8, 'J', 4, 'vip'),
(8, 'J', 5, 'vip'),
(8, 'J', 6, 'vip'),
(8, 'J', 7, 'vip'),
(8, 'J', 8, 'vip'),
(8, 'J', 9, 'vip'),
(8, 'J', 10, 'vip'),
(8, 'J', 11, 'vip'),
(8, 'J', 12, 'vip'),
(8, 'J', 13, 'vip'),
(8, 'J', 14, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(9, 'A', 1, 'standard'),
(9, 'A', 2, 'standard'),
(9, 'A', 3, 'standard'),
(9, 'A', 4, 'standard'),
(9, 'A', 5, 'standard'),
(9, 'A', 6, 'standard'),
(9, 'A', 7, 'standard'),
(9, 'A', 8, 'standard'),
(9, 'A', 9, 'standard'),
(9, 'A', 10, 'standard'),
(9, 'B', 1, 'standard'),
(9, 'B', 2, 'standard'),
(9, 'B', 3, 'standard'),
(9, 'B', 4, 'standard'),
(9, 'B', 5, 'standard'),
(9, 'B', 6, 'standard'),
(9, 'B', 7, 'standard'),
(9, 'B', 8, 'standard'),
(9, 'B', 9, 'standard'),
(9, 'B', 10, 'standard'),
(9, 'C', 1, 'standard'),
(9, 'C', 2, 'standard'),
(9, 'C', 3, 'standard'),
(9, 'C', 4, 'standard'),
(9, 'C', 5, 'standard'),
(9, 'C', 6, 'standard'),
(9, 'C', 7, 'standard'),
(9, 'C', 8, 'standard'),
(9, 'C', 9, 'standard'),
(9, 'C', 10, 'standard'),
(9, 'D', 1, 'standard'),
(9, 'D', 2, 'standard'),
(9, 'D', 3, 'standard'),
(9, 'D', 4, 'standard'),
(9, 'D', 5, 'standard'),
(9, 'D', 6, 'standard'),
(9, 'D', 7, 'standard'),
(9, 'D', 8, 'standard'),
(9, 'D', 9, 'standard'),
(9, 'D', 10, 'standard'),
(9, 'E', 1, 'standard'),
(9, 'E', 2, 'standard'),
(9, 'E', 3, 'standard'),
(9, 'E', 4, 'standard'),
(9, 'E', 5, 'standard'),
(9, 'E', 6, 'standard'),
(9, 'E', 7, 'standard'),
(9, 'E', 8, 'standard'),
(9, 'E', 9, 'standard'),
(9, 'E', 10, 'standard'),
(9, 'F', 1, 'standard'),
(9, 'F', 2, 'standard'),
(9, 'F', 3, 'standard'),
(9, 'F', 4, 'standard'),
(9, 'F', 5, 'standard'),
(9, 'F', 6, 'standard'),
(9, 'F', 7, 'standard'),
(9, 'F', 8, 'standard'),
(9, 'F', 9, 'standard'),
(9, 'F', 10, 'standard'),
(9, 'G', 1, 'standard'),
(9, 'G', 2, 'standard'),
(9, 'G', 3, 'standard'),
(9, 'G', 4, 'standard'),
(9, 'G', 5, 'standard'),
(9, 'G', 6, 'standard'),
(9, 'G', 7, 'standard'),
(9, 'G', 8, 'standard'),
(9, 'G', 9, 'standard'),
(9, 'G', 10, 'standard'),
(9, 'H', 1, 'vip'),
(9, 'H', 2, 'vip'),
(9, 'H', 3, 'vip'),
(9, 'H', 4, 'vip'),
(9, 'H', 5, 'vip'),
(9, 'H', 6, 'vip'),
(9, 'H', 7, 'vip'),
(9, 'H', 8, 'vip'),
(9, 'H', 9, 'vip'),
(9, 'H', 10, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(10, 'A', 1, 'standard'),
(10, 'A', 2, 'standard'),
(10, 'A', 3, 'standard'),
(10, 'A', 4, 'standard'),
(10, 'A', 5, 'standard'),
(10, 'A', 6, 'standard'),
(10, 'A', 7, 'standard'),
(10, 'A', 8, 'standard'),
(10, 'A', 9, 'standard'),
(10, 'A', 10, 'standard'),
(10, 'A', 11, 'standard'),
(10, 'A', 12, 'standard'),
(10, 'B', 1, 'standard'),
(10, 'B', 2, 'standard'),
(10, 'B', 3, 'standard'),
(10, 'B', 4, 'standard'),
(10, 'B', 5, 'standard'),
(10, 'B', 6, 'standard'),
(10, 'B', 7, 'standard'),
(10, 'B', 8, 'standard'),
(10, 'B', 9, 'standard'),
(10, 'B', 10, 'standard'),
(10, 'B', 11, 'standard'),
(10, 'B', 12, 'standard'),
(10, 'C', 1, 'standard'),
(10, 'C', 2, 'standard'),
(10, 'C', 3, 'standard'),
(10, 'C', 4, 'standard'),
(10, 'C', 5, 'standard'),
(10, 'C', 6, 'standard'),
(10, 'C', 7, 'standard'),
(10, 'C', 8, 'standard'),
(10, 'C', 9, 'standard'),
(10, 'C', 10, 'standard'),
(10, 'C', 11, 'standard'),
(10, 'C', 12, 'standard'),
(10, 'D', 1, 'standard'),
(10, 'D', 2, 'standard'),
(10, 'D', 3, 'standard'),
(10, 'D', 4, 'standard'),
(10, 'D', 5, 'standard'),
(10, 'D', 6, 'standard'),
(10, 'D', 7, 'standard'),
(10, 'D', 8, 'standard'),
(10, 'D', 9, 'standard'),
(10, 'D', 10, 'standard'),
(10, 'D', 11, 'standard'),
(10, 'D', 12, 'standard'),
(10, 'E', 1, 'standard'),
(10, 'E', 2, 'standard'),
(10, 'E', 3, 'standard'),
(10, 'E', 4, 'standard'),
(10, 'E', 5, 'standard'),
(10, 'E', 6, 'standard'),
(10, 'E', 7, 'standard'),
(10, 'E', 8, 'standard'),
(10, 'E', 9, 'standard'),
(10, 'E', 10, 'standard'),
(10, 'E', 11, 'standard'),
(10, 'E', 12, 'standard'),
(10, 'F', 1, 'standard'),
(10, 'F', 2, 'standard'),
(10, 'F', 3, 'standard'),
(10, 'F', 4, 'standard'),
(10, 'F', 5, 'standard'),
(10, 'F', 6, 'standard'),
(10, 'F', 7, 'standard'),
(10, 'F', 8, 'standard'),
(10, 'F', 9, 'standard'),
(10, 'F', 10, 'standard'),
(10, 'F', 11, 'standard'),
(10, 'F', 12, 'standard'),
(10, 'G', 1, 'standard'),
(10, 'G', 2, 'standard'),
(10, 'G', 3, 'standard'),
(10, 'G', 4, 'standard'),
(10, 'G', 5, 'standard'),
(10, 'G', 6, 'standard'),
(10, 'G', 7, 'standard'),
(10, 'G', 8, 'standard'),
(10, 'G', 9, 'standard'),
(10, 'G', 10, 'standard'),
(10, 'G', 11, 'standard'),
(10, 'G', 12, 'standard'),
(10, 'H', 1, 'standard'),
(10, 'H', 2, 'standard'),
(10, 'H', 3, 'standard'),
(10, 'H', 4, 'standard'),
(10, 'H', 5, 'standard'),
(10, 'H', 6, 'standard'),
(10, 'H', 7, 'standard'),
(10, 'H', 8, 'standard'),
(10, 'H', 9, 'standard'),
(10, 'H', 10, 'standard'),
(10, 'H', 11, 'standard'),
(10, 'H', 12, 'standard'),
(10, 'I', 1, 'vip'),
(10, 'I', 2, 'vip'),
(10, 'I', 3, 'vip'),
(10, 'I', 4, 'vip'),
(10, 'I', 5, 'vip'),
(10, 'I', 6, 'vip'),
(10, 'I', 7, 'vip'),
(10, 'I', 8, 'vip'),
(10, 'I', 9, 'vip'),
(10, 'I', 10, 'vip'),
(10, 'I', 11, 'vip'),
(10, 'I', 12, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(11, 'A', 1, 'standard'),
(11, 'A', 2, 'standard'),
(11, 'A', 3, 'standard'),
(11, 'A', 4, 'standard'),
(11, 'A', 5, 'standard'),
(11, 'A', 6, 'standard'),
(11, 'A', 7, 'standard'),
(11, 'A', 8, 'standard'),
(11, 'A', 9, 'standard'),
(11, 'A', 10, 'standard'),
(11, 'A', 11, 'standard'),
(11, 'A', 12, 'standard'),
(11, 'A', 13, 'standard'),
(11, 'A', 14, 'standard'),
(11, 'B', 1, 'standard'),
(11, 'B', 2, 'standard'),
(11, 'B', 3, 'standard'),
(11, 'B', 4, 'standard'),
(11, 'B', 5, 'standard'),
(11, 'B', 6, 'standard'),
(11, 'B', 7, 'standard'),
(11, 'B', 8, 'standard'),
(11, 'B', 9, 'standard'),
(11, 'B', 10, 'standard'),
(11, 'B', 11, 'standard'),
(11, 'B', 12, 'standard'),
(11, 'B', 13, 'standard'),
(11, 'B', 14, 'standard'),
(11, 'C', 1, 'standard'),
(11, 'C', 2, 'standard'),
(11, 'C', 3, 'standard'),
(11, 'C', 4, 'standard'),
(11, 'C', 5, 'standard'),
(11, 'C', 6, 'standard'),
(11, 'C', 7, 'standard'),
(11, 'C', 8, 'standard'),
(11, 'C', 9, 'standard'),
(11, 'C', 10, 'standard'),
(11, 'C', 11, 'standard'),
(11, 'C', 12, 'standard'),
(11, 'C', 13, 'standard'),
(11, 'C', 14, 'standard'),
(11, 'D', 1, 'standard'),
(11, 'D', 2, 'standard'),
(11, 'D', 3, 'standard'),
(11, 'D', 4, 'standard'),
(11, 'D', 5, 'standard'),
(11, 'D', 6, 'standard'),
(11, 'D', 7, 'standard'),
(11, 'D', 8, 'standard'),
(11, 'D', 9, 'standard'),
(11, 'D', 10, 'standard'),
(11, 'D', 11, 'standard'),
(11, 'D', 12, 'standard'),
(11, 'D', 13, 'standard'),
(11, 'D', 14, 'standard'),
(11, 'E', 1, 'standard'),
(11, 'E', 2, 'standard'),
(11, 'E', 3, 'standard'),
(11, 'E', 4, 'standard'),
(11, 'E', 5, 'standard'),
(11, 'E', 6, 'standard'),
(11, 'E', 7, 'standard'),
(11, 'E', 8, 'standard'),
(11, 'E', 9, 'standard'),
(11, 'E', 10, 'standard'),
(11, 'E', 11, 'standard'),
(11, 'E', 12, 'standard'),
(11, 'E', 13, 'standard'),
(11, 'E', 14, 'standard'),
(11, 'F', 1, 'standard'),
(11, 'F', 2, 'standard'),
(11, 'F', 3, 'standard'),
(11, 'F', 4, 'standard'),
(11, 'F', 5, 'standard'),
(11, 'F', 6, 'standard'),
(11, 'F', 7, 'standard'),
(11, 'F', 8, 'standard'),
(11, 'F', 9, 'standard'),
(11, 'F', 10, 'standard'),
(11, 'F', 11, 'standard'),
(11, 'F', 12, 'standard'),
(11, 'F', 13, 'standard'),
(11, 'F', 14, 'standard'),
(11, 'G', 1, 'standard'),
(11, 'G', 2, 'standard'),
(11, 'G', 3, 'standard'),
(11, 'G', 4, 'standard'),
(11, 'G', 5, 'standard'),
(11, 'G', 6, 'standard'),
(11, 'G', 7, 'standard'),
(11, 'G', 8, 'standard'),
(11, 'G', 9, 'standard'),
(11, 'G', 10, 'standard'),
(11, 'G', 11, 'standard'),
(11, 'G', 12, 'standard'),
(11, 'G', 13, 'standard'),
(11, 'G', 14, 'standard'),
(11, 'H', 1, 'standard'),
(11, 'H', 2, 'standard'),
(11, 'H', 3, 'standard'),
(11, 'H', 4, 'standard'),
(11, 'H', 5, 'standard'),
(11, 'H', 6, 'standard'),
(11, 'H', 7, 'standard'),
(11, 'H', 8, 'standard'),
(11, 'H', 9, 'standard'),
(11, 'H', 10, 'standard'),
(11, 'H', 11, 'standard'),
(11, 'H', 12, 'standard'),
(11, 'H', 13, 'standard'),
(11, 'H', 14, 'standard'),
(11, 'I', 1, 'standard'),
(11, 'I', 2, 'standard'),
(11, 'I', 3, 'standard'),
(11, 'I', 4, 'standard'),
(11, 'I', 5, 'standard'),
(11, 'I', 6, 'standard'),
(11, 'I', 7, 'standard'),
(11, 'I', 8, 'standard'),
(11, 'I', 9, 'standard'),
(11, 'I', 10, 'standard'),
(11, 'I', 11, 'standard'),
(11, 'I', 12, 'standard'),
(11, 'I', 13, 'standard'),
(11, 'I', 14, 'standard'),
(11, 'J', 1, 'vip'),
(11, 'J', 2, 'vip'),
(11, 'J', 3, 'vip'),
(11, 'J', 4, 'vip'),
(11, 'J', 5, 'vip'),
(11, 'J', 6, 'vip'),
(11, 'J', 7, 'vip'),
(11, 'J', 8, 'vip'),
(11, 'J', 9, 'vip'),
(11, 'J', 10, 'vip'),
(11, 'J', 11, 'vip'),
(11, 'J', 12, 'vip'),
(11, 'J', 13, 'vip'),
(11, 'J', 14, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(12, 'A', 1, 'standard'),
(12, 'A', 2, 'standard'),
(12, 'A', 3, 'standard'),
(12, 'A', 4, 'standard'),
(12, 'A', 5, 'standard'),
(12, 'A', 6, 'standard'),
(12, 'A', 7, 'standard'),
(12, 'A', 8, 'standard'),
(12, 'A', 9, 'standard'),
(12, 'A', 10, 'standard'),
(12, 'B', 1, 'standard'),
(12, 'B', 2, 'standard'),
(12, 'B', 3, 'standard'),
(12, 'B', 4, 'standard'),
(12, 'B', 5, 'standard'),
(12, 'B', 6, 'standard'),
(12, 'B', 7, 'standard'),
(12, 'B', 8, 'standard'),
(12, 'B', 9, 'standard'),
(12, 'B', 10, 'standard'),
(12, 'C', 1, 'standard'),
(12, 'C', 2, 'standard'),
(12, 'C', 3, 'standard'),
(12, 'C', 4, 'standard'),
(12, 'C', 5, 'standard'),
(12, 'C', 6, 'standard'),
(12, 'C', 7, 'standard'),
(12, 'C', 8, 'standard'),
(12, 'C', 9, 'standard'),
(12, 'C', 10, 'standard'),
(12, 'D', 1, 'standard'),
(12, 'D', 2, 'standard'),
(12, 'D', 3, 'standard'),
(12, 'D', 4, 'standard'),
(12, 'D', 5, 'standard'),
(12, 'D', 6, 'standard'),
(12, 'D', 7, 'standard'),
(12, 'D', 8, 'standard'),
(12, 'D', 9, 'standard'),
(12, 'D', 10, 'standard'),
(12, 'E', 1, 'standard'),
(12, 'E', 2, 'standard'),
(12, 'E', 3, 'standard'),
(12, 'E', 4, 'standard'),
(12, 'E', 5, 'standard'),
(12, 'E', 6, 'standard'),
(12, 'E', 7, 'standard'),
(12, 'E', 8, 'standard'),
(12, 'E', 9, 'standard'),
(12, 'E', 10, 'standard'),
(12, 'F', 1, 'standard'),
(12, 'F', 2, 'standard'),
(12, 'F', 3, 'standard'),
(12, 'F', 4, 'standard'),
(12, 'F', 5, 'standard'),
(12, 'F', 6, 'standard'),
(12, 'F', 7, 'standard'),
(12, 'F', 8, 'standard'),
(12, 'F', 9, 'standard'),
(12, 'F', 10, 'standard'),
(12, 'G', 1, 'standard'),
(12, 'G', 2, 'standard'),
(12, 'G', 3, 'standard'),
(12, 'G', 4, 'standard'),
(12, 'G', 5, 'standard'),
(12, 'G', 6, 'standard'),
(12, 'G', 7, 'standard'),
(12, 'G', 8, 'standard'),
(12, 'G', 9, 'standard'),
(12, 'G', 10, 'standard'),
(12, 'H', 1, 'vip'),
(12, 'H', 2, 'vip'),
(12, 'H', 3, 'vip'),
(12, 'H', 4, 'vip'),
(12, 'H', 5, 'vip'),
(12, 'H', 6, 'vip'),
(12, 'H', 7, 'vip'),
(12, 'H', 8, 'vip'),
(12, 'H', 9, 'vip'),
(12, 'H', 10, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(13, 'A', 1, 'standard'),
(13, 'A', 2, 'standard'),
(13, 'A', 3, 'standard'),
(13, 'A', 4, 'standard'),
(13, 'A', 5, 'standard'),
(13, 'A', 6, 'standard'),
(13, 'A', 7, 'standard'),
(13, 'A', 8, 'standard'),
(13, 'A', 9, 'standard'),
(13, 'A', 10, 'standard'),
(13, 'A', 11, 'standard'),
(13, 'A', 12, 'standard'),
(13, 'B', 1, 'standard'),
(13, 'B', 2, 'standard'),
(13, 'B', 3, 'standard'),
(13, 'B', 4, 'standard'),
(13, 'B', 5, 'standard'),
(13, 'B', 6, 'standard'),
(13, 'B', 7, 'standard'),
(13, 'B', 8, 'standard'),
(13, 'B', 9, 'standard'),
(13, 'B', 10, 'standard'),
(13, 'B', 11, 'standard'),
(13, 'B', 12, 'standard'),
(13, 'C', 1, 'standard'),
(13, 'C', 2, 'standard'),
(13, 'C', 3, 'standard'),
(13, 'C', 4, 'standard'),
(13, 'C', 5, 'standard'),
(13, 'C', 6, 'standard'),
(13, 'C', 7, 'standard'),
(13, 'C', 8, 'standard'),
(13, 'C', 9, 'standard'),
(13, 'C', 10, 'standard'),
(13, 'C', 11, 'standard'),
(13, 'C', 12, 'standard'),
(13, 'D', 1, 'standard'),
(13, 'D', 2, 'standard'),
(13, 'D', 3, 'standard'),
(13, 'D', 4, 'standard'),
(13, 'D', 5, 'standard'),
(13, 'D', 6, 'standard'),
(13, 'D', 7, 'standard'),
(13, 'D', 8, 'standard'),
(13, 'D', 9, 'standard'),
(13, 'D', 10, 'standard'),
(13, 'D', 11, 'standard'),
(13, 'D', 12, 'standard'),
(13, 'E', 1, 'standard'),
(13, 'E', 2, 'standard'),
(13, 'E', 3, 'standard'),
(13, 'E', 4, 'standard'),
(13, 'E', 5, 'standard'),
(13, 'E', 6, 'standard'),
(13, 'E', 7, 'standard'),
(13, 'E', 8, 'standard'),
(13, 'E', 9, 'standard'),
(13, 'E', 10, 'standard'),
(13, 'E', 11, 'standard'),
(13, 'E', 12, 'standard'),
(13, 'F', 1, 'standard'),
(13, 'F', 2, 'standard'),
(13, 'F', 3, 'standard'),
(13, 'F', 4, 'standard'),
(13, 'F', 5, 'standard'),
(13, 'F', 6, 'standard'),
(13, 'F', 7, 'standard'),
(13, 'F', 8, 'standard'),
(13, 'F', 9, 'standard'),
(13, 'F', 10, 'standard'),
(13, 'F', 11, 'standard'),
(13, 'F', 12, 'standard'),
(13, 'G', 1, 'standard'),
(13, 'G', 2, 'standard'),
(13, 'G', 3, 'standard'),
(13, 'G', 4, 'standard'),
(13, 'G', 5, 'standard'),
(13, 'G', 6, 'standard'),
(13, 'G', 7, 'standard'),
(13, 'G', 8, 'standard'),
(13, 'G', 9, 'standard'),
(13, 'G', 10, 'standard'),
(13, 'G', 11, 'standard'),
(13, 'G', 12, 'standard'),
(13, 'H', 1, 'standard'),
(13, 'H', 2, 'standard'),
(13, 'H', 3, 'standard'),
(13, 'H', 4, 'standard'),
(13, 'H', 5, 'standard'),
(13, 'H', 6, 'standard'),
(13, 'H', 7, 'standard'),
(13, 'H', 8, 'standard'),
(13, 'H', 9, 'standard'),
(13, 'H', 10, 'standard'),
(13, 'H', 11, 'standard'),
(13, 'H', 12, 'standard'),
(13, 'I', 1, 'vip'),
(13, 'I', 2, 'vip'),
(13, 'I', 3, 'vip'),
(13, 'I', 4, 'vip'),
(13, 'I', 5, 'vip'),
(13, 'I', 6, 'vip'),
(13, 'I', 7, 'vip'),
(13, 'I', 8, 'vip'),
(13, 'I', 9, 'vip'),
(13, 'I', 10, 'vip'),
(13, 'I', 11, 'vip'),
(13, 'I', 12, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(14, 'A', 1, 'standard'),
(14, 'A', 2, 'standard'),
(14, 'A', 3, 'standard'),
(14, 'A', 4, 'standard'),
(14, 'A', 5, 'standard'),
(14, 'A', 6, 'standard'),
(14, 'A', 7, 'standard'),
(14, 'A', 8, 'standard'),
(14, 'A', 9, 'standard'),
(14, 'A', 10, 'standard'),
(14, 'A', 11, 'standard'),
(14, 'A', 12, 'standard'),
(14, 'A', 13, 'standard'),
(14, 'A', 14, 'standard'),
(14, 'B', 1, 'standard'),
(14, 'B', 2, 'standard'),
(14, 'B', 3, 'standard'),
(14, 'B', 4, 'standard'),
(14, 'B', 5, 'standard'),
(14, 'B', 6, 'standard'),
(14, 'B', 7, 'standard'),
(14, 'B', 8, 'standard'),
(14, 'B', 9, 'standard'),
(14, 'B', 10, 'standard'),
(14, 'B', 11, 'standard'),
(14, 'B', 12, 'standard'),
(14, 'B', 13, 'standard'),
(14, 'B', 14, 'standard'),
(14, 'C', 1, 'standard'),
(14, 'C', 2, 'standard'),
(14, 'C', 3, 'standard'),
(14, 'C', 4, 'standard'),
(14, 'C', 5, 'standard'),
(14, 'C', 6, 'standard'),
(14, 'C', 7, 'standard'),
(14, 'C', 8, 'standard'),
(14, 'C', 9, 'standard'),
(14, 'C', 10, 'standard'),
(14, 'C', 11, 'standard'),
(14, 'C', 12, 'standard'),
(14, 'C', 13, 'standard'),
(14, 'C', 14, 'standard'),
(14, 'D', 1, 'standard'),
(14, 'D', 2, 'standard'),
(14, 'D', 3, 'standard'),
(14, 'D', 4, 'standard'),
(14, 'D', 5, 'standard'),
(14, 'D', 6, 'standard'),
(14, 'D', 7, 'standard'),
(14, 'D', 8, 'standard'),
(14, 'D', 9, 'standard'),
(14, 'D', 10, 'standard'),
(14, 'D', 11, 'standard'),
(14, 'D', 12, 'standard'),
(14, 'D', 13, 'standard'),
(14, 'D', 14, 'standard'),
(14, 'E', 1, 'standard'),
(14, 'E', 2, 'standard'),
(14, 'E', 3, 'standard'),
(14, 'E', 4, 'standard'),
(14, 'E', 5, 'standard'),
(14, 'E', 6, 'standard'),
(14, 'E', 7, 'standard'),
(14, 'E', 8, 'standard'),
(14, 'E', 9, 'standard'),
(14, 'E', 10, 'standard'),
(14, 'E', 11, 'standard'),
(14, 'E', 12, 'standard'),
(14, 'E', 13, 'standard'),
(14, 'E', 14, 'standard'),
(14, 'F', 1, 'standard'),
(14, 'F', 2, 'standard'),
(14, 'F', 3, 'standard'),
(14, 'F', 4, 'standard'),
(14, 'F', 5, 'standard'),
(14, 'F', 6, 'standard'),
(14, 'F', 7, 'standard'),
(14, 'F', 8, 'standard'),
(14, 'F', 9, 'standard'),
(14, 'F', 10, 'standard'),
(14, 'F', 11, 'standard'),
(14, 'F', 12, 'standard'),
(14, 'F', 13, 'standard'),
(14, 'F', 14, 'standard'),
(14, 'G', 1, 'standard'),
(14, 'G', 2, 'standard'),
(14, 'G', 3, 'standard'),
(14, 'G', 4, 'standard'),
(14, 'G', 5, 'standard'),
(14, 'G', 6, 'standard'),
(14, 'G', 7, 'standard'),
(14, 'G', 8, 'standard'),
(14, 'G', 9, 'standard'),
(14, 'G', 10, 'standard'),
(14, 'G', 11, 'standard'),
(14, 'G', 12, 'standard'),
(14, 'G', 13, 'standard'),
(14, 'G', 14, 'standard'),
(14, 'H', 1, 'standard'),
(14, 'H', 2, 'standard'),
(14, 'H', 3, 'standard'),
(14, 'H', 4, 'standard'),
(14, 'H', 5, 'standard'),
(14, 'H', 6, 'standard'),
(14, 'H', 7, 'standard'),
(14, 'H', 8, 'standard'),
(14, 'H', 9, 'standard'),
(14, 'H', 10, 'standard'),
(14, 'H', 11, 'standard'),
(14, 'H', 12, 'standard'),
(14, 'H', 13, 'standard'),
(14, 'H', 14, 'standard'),
(14, 'I', 1, 'standard'),
(14, 'I', 2, 'standard'),
(14, 'I', 3, 'standard'),
(14, 'I', 4, 'standard'),
(14, 'I', 5, 'standard'),
(14, 'I', 6, 'standard'),
(14, 'I', 7, 'standard'),
(14, 'I', 8, 'standard'),
(14, 'I', 9, 'standard'),
(14, 'I', 10, 'standard'),
(14, 'I', 11, 'standard'),
(14, 'I', 12, 'standard'),
(14, 'I', 13, 'standard'),
(14, 'I', 14, 'standard'),
(14, 'J', 1, 'vip'),
(14, 'J', 2, 'vip'),
(14, 'J', 3, 'vip'),
(14, 'J', 4, 'vip'),
(14, 'J', 5, 'vip'),
(14, 'J', 6, 'vip'),
(14, 'J', 7, 'vip'),
(14, 'J', 8, 'vip'),
(14, 'J', 9, 'vip'),
(14, 'J', 10, 'vip'),
(14, 'J', 11, 'vip'),
(14, 'J', 12, 'vip'),
(14, 'J', 13, 'vip'),
(14, 'J', 14, 'vip');
INSERT INTO seats (screen_id, seat_row, seat_number, seat_type) VALUES
(15, 'A', 1, 'standard'),
(15, 'A', 2, 'standard'),
(15, 'A', 3, 'standard'),
(15, 'A', 4, 'standard'),
(15, 'A', 5, 'standard'),
(15, 'A', 6, 'standard'),
(15, 'A', 7, 'standard'),
(15, 'A', 8, 'standard'),
(15, 'A', 9, 'standard'),
(15, 'A', 10, 'standard'),
(15, 'B', 1, 'standard'),
(15, 'B', 2, 'standard'),
(15, 'B', 3, 'standard'),
(15, 'B', 4, 'standard'),
(15, 'B', 5, 'standard'),
(15, 'B', 6, 'standard'),
(15, 'B', 7, 'standard'),
(15, 'B', 8, 'standard'),
(15, 'B', 9, 'standard'),
(15, 'B', 10, 'standard'),
(15, 'C', 1, 'standard'),
(15, 'C', 2, 'standard'),
(15, 'C', 3, 'standard'),
(15, 'C', 4, 'standard'),
(15, 'C', 5, 'standard'),
(15, 'C', 6, 'standard'),
(15, 'C', 7, 'standard'),
(15, 'C', 8, 'standard'),
(15, 'C', 9, 'standard'),
(15, 'C', 10, 'standard'),
(15, 'D', 1, 'standard'),
(15, 'D', 2, 'standard'),
(15, 'D', 3, 'standard'),
(15, 'D', 4, 'standard'),
(15, 'D', 5, 'standard'),
(15, 'D', 6, 'standard'),
(15, 'D', 7, 'standard'),
(15, 'D', 8, 'standard'),
(15, 'D', 9, 'standard'),
(15, 'D', 10, 'standard'),
(15, 'E', 1, 'standard'),
(15, 'E', 2, 'standard'),
(15, 'E', 3, 'standard'),
(15, 'E', 4, 'standard'),
(15, 'E', 5, 'standard'),
(15, 'E', 6, 'standard'),
(15, 'E', 7, 'standard'),
(15, 'E', 8, 'standard'),
(15, 'E', 9, 'standard'),
(15, 'E', 10, 'standard'),
(15, 'F', 1, 'standard'),
(15, 'F', 2, 'standard'),
(15, 'F', 3, 'standard'),
(15, 'F', 4, 'standard'),
(15, 'F', 5, 'standard'),
(15, 'F', 6, 'standard'),
(15, 'F', 7, 'standard'),
(15, 'F', 8, 'standard'),
(15, 'F', 9, 'standard'),
(15, 'F', 10, 'standard'),
(15, 'G', 1, 'standard'),
(15, 'G', 2, 'standard'),
(15, 'G', 3, 'standard'),
(15, 'G', 4, 'standard'),
(15, 'G', 5, 'standard'),
(15, 'G', 6, 'standard'),
(15, 'G', 7, 'standard'),
(15, 'G', 8, 'standard'),
(15, 'G', 9, 'standard'),
(15, 'G', 10, 'standard'),
(15, 'H', 1, 'vip'),
(15, 'H', 2, 'vip'),
(15, 'H', 3, 'vip'),
(15, 'H', 4, 'vip'),
(15, 'H', 5, 'vip'),
(15, 'H', 6, 'vip'),
(15, 'H', 7, 'vip'),
(15, 'H', 8, 'vip'),
(15, 'H', 9, 'vip'),
(15, 'H', 10, 'vip');

-- SHOWTIMES
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (1, 1, 2, '2026-08-01', '12:30:00', '15:08:00', 'Spanish', '3D', 14.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (1, 1, 3, '2026-08-01', '15:00:00', '17:38:00', 'French', 'IMAX', 17.50, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (1, 2, 4, '2026-08-01', '18:00:00', '20:38:00', 'English', '4DX', 21.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (2, 1, 3, '2026-08-01', '15:00:00', '17:24:00', 'French', 'IMAX', 16.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (2, 2, 4, '2026-08-01', '18:00:00', '20:24:00', 'English', '4DX', 19.50, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (3, 2, 4, '2026-08-01', '18:00:00', '20:09:00', 'English', '4DX', 18.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (3, 2, 5, '2026-08-01', '21:00:00', '23:09:00', 'Spanish', 'VIP', 21.50, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (3, 2, 6, '2026-08-01', '10:00:00', '12:09:00', 'French', '2D', 15.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (4, 2, 5, '2026-08-01', '21:00:00', '23:31:00', 'Spanish', 'VIP', 20.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (4, 2, 6, '2026-08-01', '10:00:00', '12:31:00', 'French', '2D', 13.50, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (5, 2, 6, '2026-08-01', '10:00:00', '12:01:00', 'French', '2D', 12.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (5, 3, 7, '2026-08-01', '12:30:00', '14:31:00', 'English', '3D', 15.50, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (5, 3, 8, '2026-08-01', '15:00:00', '17:01:00', 'Spanish', 'IMAX', 19.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (6, 3, 7, '2026-08-01', '12:30:00', '14:27:00', 'English', '3D', 14.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (6, 3, 8, '2026-08-01', '15:00:00', '16:57:00', 'Spanish', 'IMAX', 17.50, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (7, 3, 8, '2026-08-01', '15:00:00', '17:16:00', 'Spanish', 'IMAX', 16.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (7, 3, 9, '2026-08-01', '18:00:00', '20:16:00', 'French', '4DX', 19.50, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (7, 4, 10, '2026-08-01', '21:00:00', '23:16:00', 'English', 'VIP', 23.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (8, 3, 9, '2026-08-01', '18:00:00', '19:58:00', 'French', '4DX', 18.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (8, 4, 10, '2026-08-01', '21:00:00', '22:58:00', 'English', 'VIP', 21.50, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (9, 4, 10, '2026-08-01', '21:00:00', '22:54:00', 'English', 'VIP', 20.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (9, 4, 11, '2026-08-01', '10:00:00', '11:54:00', 'Spanish', '2D', 13.50, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (9, 4, 12, '2026-08-01', '12:30:00', '14:24:00', 'French', '3D', 17.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (10, 4, 11, '2026-08-01', '10:00:00', '12:22:00', 'Spanish', '2D', 12.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (10, 4, 12, '2026-08-01', '12:30:00', '14:52:00', 'French', '3D', 15.50, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (1, 1, 3, '2026-08-02', '12:30:00', '15:08:00', 'Spanish', 'IMAX', 16.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (1, 2, 4, '2026-08-02', '15:00:00', '17:38:00', 'French', '4DX', 19.50, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (1, 2, 5, '2026-08-02', '18:00:00', '20:38:00', 'English', 'VIP', 23.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (2, 2, 4, '2026-08-02', '15:00:00', '17:24:00', 'French', '4DX', 18.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (2, 2, 5, '2026-08-02', '18:00:00', '20:24:00', 'English', 'VIP', 21.50, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (3, 2, 5, '2026-08-02', '18:00:00', '20:09:00', 'English', 'VIP', 20.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (3, 2, 6, '2026-08-02', '21:00:00', '23:09:00', 'Spanish', '2D', 13.50, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (3, 3, 7, '2026-08-02', '10:00:00', '12:09:00', 'French', '3D', 17.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (4, 2, 6, '2026-08-02', '21:00:00', '23:31:00', 'Spanish', '2D', 12.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (4, 3, 7, '2026-08-02', '10:00:00', '12:31:00', 'French', '3D', 15.50, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (5, 3, 7, '2026-08-02', '10:00:00', '12:01:00', 'French', '3D', 14.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (5, 3, 8, '2026-08-02', '12:30:00', '14:31:00', 'English', 'IMAX', 17.50, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (5, 3, 9, '2026-08-02', '15:00:00', '17:01:00', 'Spanish', '4DX', 21.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (6, 3, 8, '2026-08-02', '12:30:00', '14:27:00', 'English', 'IMAX', 16.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (6, 3, 9, '2026-08-02', '15:00:00', '16:57:00', 'Spanish', '4DX', 19.50, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (7, 3, 9, '2026-08-02', '15:00:00', '17:16:00', 'Spanish', '4DX', 18.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (7, 4, 10, '2026-08-02', '18:00:00', '20:16:00', 'French', 'VIP', 21.50, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (7, 4, 11, '2026-08-02', '21:00:00', '23:16:00', 'English', '2D', 15.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (8, 4, 10, '2026-08-02', '18:00:00', '19:58:00', 'French', 'VIP', 20.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (8, 4, 11, '2026-08-02', '21:00:00', '22:58:00', 'English', '2D', 13.50, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (9, 4, 11, '2026-08-02', '21:00:00', '22:54:00', 'English', '2D', 12.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (9, 4, 12, '2026-08-02', '10:00:00', '11:54:00', 'Spanish', '3D', 15.50, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (9, 5, 13, '2026-08-02', '12:30:00', '14:24:00', 'French', 'IMAX', 19.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (10, 4, 12, '2026-08-02', '10:00:00', '12:22:00', 'Spanish', '3D', 14.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (10, 5, 13, '2026-08-02', '12:30:00', '14:52:00', 'French', 'IMAX', 17.50, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (1, 2, 4, '2026-08-03', '12:30:00', '15:08:00', 'Spanish', '4DX', 18.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (1, 2, 5, '2026-08-03', '15:00:00', '17:38:00', 'French', 'VIP', 21.50, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (1, 2, 6, '2026-08-03', '18:00:00', '20:38:00', 'English', '2D', 15.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (2, 2, 5, '2026-08-03', '15:00:00', '17:24:00', 'French', 'VIP', 20.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (2, 2, 6, '2026-08-03', '18:00:00', '20:24:00', 'English', '2D', 13.50, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (3, 2, 6, '2026-08-03', '18:00:00', '20:09:00', 'English', '2D', 12.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (3, 3, 7, '2026-08-03', '21:00:00', '23:09:00', 'Spanish', '3D', 15.50, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (3, 3, 8, '2026-08-03', '10:00:00', '12:09:00', 'French', 'IMAX', 19.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (4, 3, 7, '2026-08-03', '21:00:00', '23:31:00', 'Spanish', '3D', 14.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (4, 3, 8, '2026-08-03', '10:00:00', '12:31:00', 'French', 'IMAX', 17.50, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (5, 3, 8, '2026-08-03', '10:00:00', '12:01:00', 'French', 'IMAX', 16.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (5, 3, 9, '2026-08-03', '12:30:00', '14:31:00', 'English', '4DX', 19.50, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (5, 4, 10, '2026-08-03', '15:00:00', '17:01:00', 'Spanish', 'VIP', 23.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (6, 3, 9, '2026-08-03', '12:30:00', '14:27:00', 'English', '4DX', 18.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (6, 4, 10, '2026-08-03', '15:00:00', '16:57:00', 'Spanish', 'VIP', 21.50, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (7, 4, 10, '2026-08-03', '15:00:00', '17:16:00', 'Spanish', 'VIP', 20.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (7, 4, 11, '2026-08-03', '18:00:00', '20:16:00', 'French', '2D', 13.50, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (7, 4, 12, '2026-08-03', '21:00:00', '23:16:00', 'English', '3D', 17.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (8, 4, 11, '2026-08-03', '18:00:00', '19:58:00', 'French', '2D', 12.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (8, 4, 12, '2026-08-03', '21:00:00', '22:58:00', 'English', '3D', 15.50, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (9, 4, 12, '2026-08-03', '21:00:00', '22:54:00', 'English', '3D', 14.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (9, 5, 13, '2026-08-03', '10:00:00', '11:54:00', 'Spanish', 'IMAX', 17.50, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (9, 5, 14, '2026-08-03', '12:30:00', '14:24:00', 'French', '4DX', 21.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (10, 5, 13, '2026-08-03', '10:00:00', '12:22:00', 'Spanish', 'IMAX', 16.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (10, 5, 14, '2026-08-03', '12:30:00', '14:52:00', 'French', '4DX', 19.50, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (1, 2, 5, '2026-08-04', '12:30:00', '15:08:00', 'Spanish', 'VIP', 20.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (1, 2, 6, '2026-08-04', '15:00:00', '17:38:00', 'French', '2D', 13.50, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (1, 3, 7, '2026-08-04', '18:00:00', '20:38:00', 'English', '3D', 17.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (2, 2, 6, '2026-08-04', '15:00:00', '17:24:00', 'French', '2D', 12.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (2, 3, 7, '2026-08-04', '18:00:00', '20:24:00', 'English', '3D', 15.50, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (3, 3, 7, '2026-08-04', '18:00:00', '20:09:00', 'English', '3D', 14.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (3, 3, 8, '2026-08-04', '21:00:00', '23:09:00', 'Spanish', 'IMAX', 17.50, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (3, 3, 9, '2026-08-04', '10:00:00', '12:09:00', 'French', '4DX', 21.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (4, 3, 8, '2026-08-04', '21:00:00', '23:31:00', 'Spanish', 'IMAX', 16.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (4, 3, 9, '2026-08-04', '10:00:00', '12:31:00', 'French', '4DX', 19.50, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (5, 3, 9, '2026-08-04', '10:00:00', '12:01:00', 'French', '4DX', 18.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (5, 4, 10, '2026-08-04', '12:30:00', '14:31:00', 'English', 'VIP', 21.50, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (5, 4, 11, '2026-08-04', '15:00:00', '17:01:00', 'Spanish', '2D', 15.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (6, 4, 10, '2026-08-04', '12:30:00', '14:27:00', 'English', 'VIP', 20.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (6, 4, 11, '2026-08-04', '15:00:00', '16:57:00', 'Spanish', '2D', 13.50, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (7, 4, 11, '2026-08-04', '15:00:00', '17:16:00', 'Spanish', '2D', 12.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (7, 4, 12, '2026-08-04', '18:00:00', '20:16:00', 'French', '3D', 15.50, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (7, 5, 13, '2026-08-04', '21:00:00', '23:16:00', 'English', 'IMAX', 19.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (8, 4, 12, '2026-08-04', '18:00:00', '19:58:00', 'French', '3D', 14.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (8, 5, 13, '2026-08-04', '21:00:00', '22:58:00', 'English', 'IMAX', 17.50, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (9, 5, 13, '2026-08-04', '21:00:00', '22:54:00', 'English', 'IMAX', 16.00, 108, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (9, 5, 14, '2026-08-04', '10:00:00', '11:54:00', 'Spanish', '4DX', 19.50, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (9, 5, 15, '2026-08-04', '12:30:00', '14:24:00', 'French', 'VIP', 23.00, 80, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (10, 5, 14, '2026-08-04', '10:00:00', '12:22:00', 'Spanish', '4DX', 18.00, 140, 'scheduled');
INSERT INTO showtimes (movie_id, theatre_id, screen_id, show_date, start_time, end_time, language, format, ticket_price, available_seats, status) VALUES (10, 5, 15, '2026-08-04', '12:30:00', '14:52:00', 'French', 'VIP', 21.50, 80, 'scheduled');

-- BOOKINGS
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (2, 2, 35.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (3, 3, 63.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (4, 4, 64.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (5, 5, 19.50, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (6, 6, 36.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (7, 7, 64.50, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (8, 8, 60.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (9, 9, 20.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (10, 10, 27.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (11, 11, 36.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (12, 12, 62.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (1, 13, 19.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (2, 14, 28.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (3, 15, 52.50, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (4, 16, 64.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (5, 17, 19.50, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (6, 18, 46.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (7, 19, 54.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (8, 20, 86.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (9, 21, 20.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (10, 22, 27.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (11, 23, 51.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (12, 24, 48.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (1, 25, 15.50, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (2, 26, 32.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (3, 27, 58.50, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (4, 28, 92.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (5, 29, 18.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (6, 30, 43.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (7, 31, 60.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (8, 32, 54.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (9, 33, 17.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (10, 34, 24.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (11, 35, 46.50, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (12, 36, 56.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (1, 37, 17.50, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (2, 38, 42.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (3, 39, 48.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (4, 40, 78.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (5, 41, 18.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (6, 42, 43.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (7, 43, 45.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (8, 44, 80.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (9, 45, 13.50, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (10, 46, 24.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (11, 47, 46.50, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (12, 48, 76.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (1, 49, 14.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (2, 50, 35.00, 'confirmed');
INSERT INTO bookings (user_id, showtime_id, total_amount, booking_status) VALUES (3, 51, 54.00, 'confirmed');

-- BOOKING SEATS (linking sample seats to bookings)
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 1, id, 17.50 FROM seats WHERE screen_id = 3 LIMIT 1 OFFSET 3;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 1, id, 17.50 FROM seats WHERE screen_id = 3 LIMIT 1 OFFSET 4;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 2, id, 21.00 FROM seats WHERE screen_id = 4 LIMIT 1 OFFSET 6;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 2, id, 21.00 FROM seats WHERE screen_id = 4 LIMIT 1 OFFSET 7;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 2, id, 21.00 FROM seats WHERE screen_id = 4 LIMIT 1 OFFSET 8;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 3, id, 16.00 FROM seats WHERE screen_id = 3 LIMIT 1 OFFSET 9;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 3, id, 16.00 FROM seats WHERE screen_id = 3 LIMIT 1 OFFSET 10;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 3, id, 16.00 FROM seats WHERE screen_id = 3 LIMIT 1 OFFSET 11;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 3, id, 16.00 FROM seats WHERE screen_id = 3 LIMIT 1 OFFSET 12;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 4, id, 19.50 FROM seats WHERE screen_id = 4 LIMIT 1 OFFSET 12;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 5, id, 18.00 FROM seats WHERE screen_id = 4 LIMIT 1 OFFSET 15;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 5, id, 18.00 FROM seats WHERE screen_id = 4 LIMIT 1 OFFSET 16;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 6, id, 21.50 FROM seats WHERE screen_id = 5 LIMIT 1 OFFSET 18;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 6, id, 21.50 FROM seats WHERE screen_id = 5 LIMIT 1 OFFSET 19;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 6, id, 21.50 FROM seats WHERE screen_id = 5 LIMIT 1 OFFSET 20;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 7, id, 15.00 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 21;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 7, id, 15.00 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 22;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 7, id, 15.00 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 23;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 7, id, 15.00 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 24;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 8, id, 20.00 FROM seats WHERE screen_id = 5 LIMIT 1 OFFSET 24;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 9, id, 13.50 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 27;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 9, id, 13.50 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 28;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 10, id, 12.00 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 30;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 10, id, 12.00 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 31;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 10, id, 12.00 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 32;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 11, id, 15.50 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 33;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 11, id, 15.50 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 34;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 11, id, 15.50 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 35;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 11, id, 15.50 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 36;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 12, id, 19.00 FROM seats WHERE screen_id = 8 LIMIT 1 OFFSET 36;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 13, id, 14.00 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 39;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 13, id, 14.00 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 40;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 14, id, 17.50 FROM seats WHERE screen_id = 8 LIMIT 1 OFFSET 42;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 14, id, 17.50 FROM seats WHERE screen_id = 8 LIMIT 1 OFFSET 43;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 14, id, 17.50 FROM seats WHERE screen_id = 8 LIMIT 1 OFFSET 44;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 15, id, 16.00 FROM seats WHERE screen_id = 8 LIMIT 1 OFFSET 45;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 15, id, 16.00 FROM seats WHERE screen_id = 8 LIMIT 1 OFFSET 46;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 15, id, 16.00 FROM seats WHERE screen_id = 8 LIMIT 1 OFFSET 47;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 15, id, 16.00 FROM seats WHERE screen_id = 8 LIMIT 1 OFFSET 48;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 16, id, 19.50 FROM seats WHERE screen_id = 9 LIMIT 1 OFFSET 48;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 17, id, 23.00 FROM seats WHERE screen_id = 10 LIMIT 1 OFFSET 51;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 17, id, 23.00 FROM seats WHERE screen_id = 10 LIMIT 1 OFFSET 52;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 18, id, 18.00 FROM seats WHERE screen_id = 9 LIMIT 1 OFFSET 54;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 18, id, 18.00 FROM seats WHERE screen_id = 9 LIMIT 1 OFFSET 55;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 18, id, 18.00 FROM seats WHERE screen_id = 9 LIMIT 1 OFFSET 56;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 19, id, 21.50 FROM seats WHERE screen_id = 10 LIMIT 1 OFFSET 57;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 19, id, 21.50 FROM seats WHERE screen_id = 10 LIMIT 1 OFFSET 58;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 19, id, 21.50 FROM seats WHERE screen_id = 10 LIMIT 1 OFFSET 59;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 19, id, 21.50 FROM seats WHERE screen_id = 10 LIMIT 1 OFFSET 60;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 20, id, 20.00 FROM seats WHERE screen_id = 10 LIMIT 1 OFFSET 60;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 21, id, 13.50 FROM seats WHERE screen_id = 11 LIMIT 1 OFFSET 63;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 21, id, 13.50 FROM seats WHERE screen_id = 11 LIMIT 1 OFFSET 64;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 22, id, 17.00 FROM seats WHERE screen_id = 12 LIMIT 1 OFFSET 66;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 22, id, 17.00 FROM seats WHERE screen_id = 12 LIMIT 1 OFFSET 67;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 22, id, 17.00 FROM seats WHERE screen_id = 12 LIMIT 1 OFFSET 68;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 23, id, 12.00 FROM seats WHERE screen_id = 11 LIMIT 1 OFFSET 69;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 23, id, 12.00 FROM seats WHERE screen_id = 11 LIMIT 1 OFFSET 70;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 23, id, 12.00 FROM seats WHERE screen_id = 11 LIMIT 1 OFFSET 71;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 23, id, 12.00 FROM seats WHERE screen_id = 11 LIMIT 1 OFFSET 72;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 24, id, 15.50 FROM seats WHERE screen_id = 12 LIMIT 1 OFFSET 72;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 25, id, 16.00 FROM seats WHERE screen_id = 3 LIMIT 1 OFFSET 75;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 25, id, 16.00 FROM seats WHERE screen_id = 3 LIMIT 1 OFFSET 76;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 26, id, 19.50 FROM seats WHERE screen_id = 4 LIMIT 1 OFFSET 78;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 26, id, 19.50 FROM seats WHERE screen_id = 4 LIMIT 1 OFFSET 79;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 26, id, 19.50 FROM seats WHERE screen_id = 4 LIMIT 1 OFFSET 80;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 27, id, 23.00 FROM seats WHERE screen_id = 5 LIMIT 1 OFFSET 81;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 27, id, 23.00 FROM seats WHERE screen_id = 5 LIMIT 1 OFFSET 82;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 27, id, 23.00 FROM seats WHERE screen_id = 5 LIMIT 1 OFFSET 83;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 27, id, 23.00 FROM seats WHERE screen_id = 5 LIMIT 1 OFFSET 84;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 28, id, 18.00 FROM seats WHERE screen_id = 4 LIMIT 1 OFFSET 84;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 29, id, 21.50 FROM seats WHERE screen_id = 5 LIMIT 1 OFFSET 87;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 29, id, 21.50 FROM seats WHERE screen_id = 5 LIMIT 1 OFFSET 88;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 30, id, 20.00 FROM seats WHERE screen_id = 5 LIMIT 1 OFFSET 90;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 30, id, 20.00 FROM seats WHERE screen_id = 5 LIMIT 1 OFFSET 91;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 30, id, 20.00 FROM seats WHERE screen_id = 5 LIMIT 1 OFFSET 92;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 31, id, 13.50 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 13;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 31, id, 13.50 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 14;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 31, id, 13.50 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 15;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 31, id, 13.50 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 16;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 32, id, 17.00 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 96;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 33, id, 12.00 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 19;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 33, id, 12.00 FROM seats WHERE screen_id = 6 LIMIT 1 OFFSET 20;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 34, id, 15.50 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 102;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 34, id, 15.50 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 103;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 34, id, 15.50 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 104;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 35, id, 14.00 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 105;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 35, id, 14.00 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 106;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 35, id, 14.00 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 107;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 35, id, 14.00 FROM seats WHERE screen_id = 7 LIMIT 1 OFFSET 0;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 36, id, 17.50 FROM seats WHERE screen_id = 8 LIMIT 1 OFFSET 108;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 37, id, 21.00 FROM seats WHERE screen_id = 9 LIMIT 1 OFFSET 31;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 37, id, 21.00 FROM seats WHERE screen_id = 9 LIMIT 1 OFFSET 32;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 38, id, 16.00 FROM seats WHERE screen_id = 8 LIMIT 1 OFFSET 114;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 38, id, 16.00 FROM seats WHERE screen_id = 8 LIMIT 1 OFFSET 115;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 38, id, 16.00 FROM seats WHERE screen_id = 8 LIMIT 1 OFFSET 116;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 39, id, 19.50 FROM seats WHERE screen_id = 9 LIMIT 1 OFFSET 37;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 39, id, 19.50 FROM seats WHERE screen_id = 9 LIMIT 1 OFFSET 38;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 39, id, 19.50 FROM seats WHERE screen_id = 9 LIMIT 1 OFFSET 39;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 39, id, 19.50 FROM seats WHERE screen_id = 9 LIMIT 1 OFFSET 40;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 40, id, 18.00 FROM seats WHERE screen_id = 9 LIMIT 1 OFFSET 40;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 41, id, 21.50 FROM seats WHERE screen_id = 10 LIMIT 1 OFFSET 15;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 41, id, 21.50 FROM seats WHERE screen_id = 10 LIMIT 1 OFFSET 16;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 42, id, 15.00 FROM seats WHERE screen_id = 11 LIMIT 1 OFFSET 126;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 42, id, 15.00 FROM seats WHERE screen_id = 11 LIMIT 1 OFFSET 127;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 42, id, 15.00 FROM seats WHERE screen_id = 11 LIMIT 1 OFFSET 128;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 43, id, 20.00 FROM seats WHERE screen_id = 10 LIMIT 1 OFFSET 21;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 43, id, 20.00 FROM seats WHERE screen_id = 10 LIMIT 1 OFFSET 22;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 43, id, 20.00 FROM seats WHERE screen_id = 10 LIMIT 1 OFFSET 23;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 43, id, 20.00 FROM seats WHERE screen_id = 10 LIMIT 1 OFFSET 24;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 44, id, 13.50 FROM seats WHERE screen_id = 11 LIMIT 1 OFFSET 132;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 45, id, 12.00 FROM seats WHERE screen_id = 11 LIMIT 1 OFFSET 135;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 45, id, 12.00 FROM seats WHERE screen_id = 11 LIMIT 1 OFFSET 136;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 46, id, 15.50 FROM seats WHERE screen_id = 12 LIMIT 1 OFFSET 58;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 46, id, 15.50 FROM seats WHERE screen_id = 12 LIMIT 1 OFFSET 59;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 46, id, 15.50 FROM seats WHERE screen_id = 12 LIMIT 1 OFFSET 60;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 47, id, 19.00 FROM seats WHERE screen_id = 13 LIMIT 1 OFFSET 33;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 47, id, 19.00 FROM seats WHERE screen_id = 13 LIMIT 1 OFFSET 34;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 47, id, 19.00 FROM seats WHERE screen_id = 13 LIMIT 1 OFFSET 35;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 47, id, 19.00 FROM seats WHERE screen_id = 13 LIMIT 1 OFFSET 36;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 48, id, 14.00 FROM seats WHERE screen_id = 12 LIMIT 1 OFFSET 64;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 49, id, 17.50 FROM seats WHERE screen_id = 13 LIMIT 1 OFFSET 39;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 49, id, 17.50 FROM seats WHERE screen_id = 13 LIMIT 1 OFFSET 40;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 50, id, 18.00 FROM seats WHERE screen_id = 4 LIMIT 1 OFFSET 42;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 50, id, 18.00 FROM seats WHERE screen_id = 4 LIMIT 1 OFFSET 43;
INSERT INTO booking_seats (booking_id, seat_id, price) SELECT 50, id, 18.00 FROM seats WHERE screen_id = 4 LIMIT 1 OFFSET 44;

-- Sync available_seats after bookings
UPDATE showtimes st SET available_seats = available_seats - (
  SELECT COUNT(*) FROM booking_seats bs
  JOIN bookings bk ON bs.booking_id = bk.id
  WHERE bk.showtime_id = st.id AND bk.booking_status = 'confirmed'
);
